import Head from 'next/head'
import { FC } from 'react'

interface Props {
  title: string
}

const CustomHead: FC<Props> = ({ title }) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by SolStake" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default CustomHead
